version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: ewm_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: dbuser
      POSTGRES_DB: stat_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d stat_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  db-setup:
    image: postgres:16.1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGHOST: postgres
      PGUSER: dbuser
      PGPASSWORD: 12345
      PGDATABASE: stat_db
    command: >
      bash -c "
        psql -c 'CREATE DATABASE ewm_db;'
        psql -c 'CREATE DATABASE user_db;'  
        psql -c 'CREATE DATABASE req_db;'
        psql -c 'CREATE DATABASE event_db;'
        psql -c 'CREATE DATABASE views_db;'
        echo 'All databases created successfully!'
      "
    restart: on-failure

volumes:
  postgres_data: