spring:
  application:
    name: request-service
  config:
    import: "configserver:"
  cloud:
    config:
      fail-fast: true
      retry:
        useRandomPolicy: true
        max-interval: 6000
        max-attempts: 3
      discovery:
        enabled: true
        serviceId: config-server


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}

grpc:
  client:
    collector:
      address: "discovery:///collector"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    analyzer:
      address: "discovery:///analyzer"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext