spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: main_service_route
              uri: lb://main-service
              predicates:
                - Path=/**


server:
  port: 8080