CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    pinned BOOLEAN
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    annotation TEXT NOT NULL,
    description TEXT,
    event_date TIMESTAMP NOT NULL,
    location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE NOT NULL,
    category_id BIGINT REFERENCES categories(id),
    initiator_id BIGINT,
    paid BOOLEAN,
    participant_limit BIGINT,
    confirmed_requests BIGINT,
    request_moderation BOOLEAN,
    state VARCHAR(50),
    created_on TIMESTAMP,
    published_on TIMESTAMP
);

CREATE TABLE IF NOT EXISTS compilations_events (
    compilation_id BIGINT REFERENCES compilations(id) ON DELETE CASCADE NOT NULL,
    event_id BIGINT REFERENCES events(id) ON DELETE CASCADE NOT NULL,
    PRIMARY KEY (compilation_id, event_id)
);