# Общие настройки, применяемые ко всем профилям
server:
  port: 9090

logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: INFO

spring:
  main:
    banner-mode: off
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6542/stat_db
    username: dbuser
    password: 12345
  
  sql:
    init:
      mode: always
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          timezone: UTC

---
# Профиль mvn spring-boot:run -Dspring-boot.run.profiles=dev
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: admin
    password: 

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        jdbc:
          timezone: UTC